---
abstract: 'more POSIX correct threads'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  Config: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  POSIX: 0
  Test::More: 0
  Thread::Queue: 0
  Thread::Semaphore: 0
  Thread::SigMask: 0
  Time::HiRes: 0
configure_requires:
  Module::Build: 0.3601
  Perl::OSType: 1
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: threads-posix
requires:
  XSLoader: 0
  parent: 0
  perl: 5.006
  strict: 0
  threads: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=threads-posix
  repository: git://github.com/Leont/threads-posix.git
version: 0.002
